#!/usr/bin/env bash

uki=$3
if [[ -z $uki ]]; then
     echo "Nothing to do"
     exit 0
fi

cert=/etc/secureboot/db.crt
key=/etc/secureboot/db.key

echo Signing "$uki" with "$cert"

if ! sbverify --cert "$cert" "$uki" &> /dev/null; then
    sbsign --key "$key" --cert "$cert" --output "$uki" "$uki"
else
    echo "$uki" is already signed with "$cert"
fi
